config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pictures#index"

  resources :pictures
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
# frozen_string_literal: true
class Picture < ApplicationRecord
  extend Dragonfly::Model::Validations

  dragonfly_accessor :file do
    after_assign { |img| img.thumb!('100x100') }
  end

  validates :file, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
# frozen_string_literal: true
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to pictures_path
      flash[:notice] = "Your picture successfully uploaded"
    else
      render :new
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  private

  def picture_params
    params.fetch(:picture, {}).permit(:file)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true
module HomeHelper
end

app/helpers/pictures_helper.rb
# frozen_string_literal: true
module PicturesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/common/_errors.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      |There was errors with picture upload:
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Vc
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
  -flash.each do |name, msg|
    =content_tag :div, msg, class: name
  ul.nav.navbar-nav
    li= link_to "Pictures index", root_path
    li= link_to 'Upload picture', new_picture_path
  = yield

app/views/pictures/index.html.slim
h1 Pictures index
-@pictures.each do |picture|
  =link_to picture_path(picture)
    =image_tag picture.file.url, class: 'picture'
br  

app/views/pictures/new.html.slim
h1 Upload picture form
=render 'common/errors', resource: @picture
=form_for @picture do |f|
  .form_group
    =f.label :file, 'Upload picture: '
    =f.file_field :file
  .form_group
    =f.submit 'Upload'  

app/views/pictures/show.html.slim
h1 Picture show
=@picture.id
br
=image_tag @picture.file.url

app/views/root/index.html.slim
.container
  .row
    =10.times do
      .block
        .image
          =image_tag 'sky.jpg', { class: 'img-responsive' }
        .text
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
    